name: pet_adoption
description: "Felvera."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.3.beta <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.1.1  # Update to the latest compatible version
  cloud_firestore: ^5.0.2  # Update to the latest compatible version
  firebase_core: ^3.1.1  # Update to the latest compatible version
  firebase_storage: ^12.1.0  # Update to the latest compatible version
  introduction_screen: ^3.1.14  # Update to the latest compatible version
  image_picker: ^1.1.2  # Update to the latest compatible version
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  carousel_slider: ^4.0.0
  # Update other dependencies as needed based on `flutter pub outdated`


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/resim.png
